/*
 * Firejack Platform - Copyright (c) 2012 Firejack Technologies
 *
 * This source code is the product of the Firejack Technologies
 * Core Technologies Team (Benjamin A. Miller, Oleg Marshalenko, and Timur
 * Asanov) and licensed only under valid, executed license agreements
 * between Firejack Technologies and its customers. Modification and / or
 * re-distribution of this source code is allowed only within the terms
 * of an executed license agreement.
 *
 * Any modification of this code voids any and all warranties and indemnifications
 * for the component in question and may interfere with upgrade path. Firejack Technologies
 * encourages you to extend the core framework and / or request modifications. You may
 * also submit and assign contributions to Firejack Technologies for consideration
 * as improvements or inclusions to the platform to restore modification
 * warranties and indemnifications upon official re-distributed in patch or release form.
 */


Ext.define('OPF.core.model.Field', {
    extend: 'Ext.data.Model',

    fields: [
        { name: 'id', type: 'int', useNull: true },
        { name: 'inherited', type: 'boolean' },
        { name: 'autoGenerated', type: 'boolean' },
        { name: 'name', type: 'string' },
        { name: 'displayName', type: 'string' },
        { name: 'displayDescription', type: 'string' },
        { name: 'fieldType', type: 'string' },
        { name: 'fieldTypeName', type: 'string' },
        { name: 'customFieldType', type: 'string' },
        { name: 'required', type: 'boolean' },
        { name: 'searchable', type: 'boolean' },
        { name: 'defaultValue', type: 'string', useNull: true },
        { name: 'description', type: 'string', useNull: true },
        { name: 'allowedValues', useNull: true },

        { name: 'parentId', type: 'int' },

        { name: 'created', type: 'int' },
        { name: 'canUpdate', type: 'boolean'},
        { name: 'canDelete', type: 'boolean'}
    ],

    associations: [
        { type: 'belongsTo', model: 'OPF.console.directory.model.Directory', primaryKey: 'id', foreignKey: 'parentId' }
    ]

});