/*
 * Firejack Platform - Copyright (c) 2011 Firejack Technologies
 *
 * This source code is the product of the Firejack Technologies
 * Core Technologies Team (Benjamin A. Miller, Oleg Marshalenko, and Timur
 * Asanov) and licensed only under valid, executed license agreements
 * between Firejack Technologies and its customers. Modification and / or
 * re-distribution of this source code is allowed only within the terms
 * of an executed license agreement.
 *
 * Any modification of this code voids any and all warranties and indemnifications
 * for the component in question and may interfere with upgrade path. Firejack Technologies
 * encourages you to extend the core framework and / or request modifications. You may
 * also submit and assign contributions to Firejack Technologies for consideration
 * as improvements or inclusions to the platform to restore modification
 * warranties and indemnifications upon official re-distributed in patch or release form.
 */

/**
 *
 */
Ext.define('OPF.console.domain.view.FieldGridFieldSet', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.fields-grid-fieldset',
    title: 'Fields',
    padding: 10,

    initComponent: function() {

        this.fieldGrid = Ext.create('Ext.grid.Panel', {
            height: 400,
            flex: 1,

            store: 'Fields',

            columns: [
                OPF.Ui.populateColumn('inherited', '!', {
                    align: 'center',
                    width: 30,
                    renderer: function(inherited, metaData, record) {
                        var iconName = 'table_';
                        var autoGenerated = record.get('autoGenerated');
                        if (autoGenerated) {
                            iconName += 'lock';
                        } else if (inherited) {
                            iconName += 'inherited';
                        } else {
                            iconName += 'own';
                        }
                        return '<img src="' + OPF.Cfg.OPF_CONSOLE_URL + '/images/icons/16/' + iconName + '_16.png">';
                    }
                }),
                OPF.Ui.populateColumn('name', 'Field', {width: 150, renderer: 'htmlEncode'}),
                OPF.Ui.populateColumn('fieldTypeName', 'Type', {width: 150}),
                OPF.Ui.populateColumn('required', 'Required', {trueText: 'Yes', falseText: 'No', width: 100}),
                OPF.Ui.populateColumn('defaultValue', 'Default', {width: 200}),
                OPF.Ui.populateColumn('allowedValues', 'Allowed Values', {flex: 1})
            ],
            tbar: [
                OPF.Ui.createBtn('Add', 50, 'add-field', {iconCls: 'silk-add'}),
                '-',
                OPF.Ui.createBtn('Delete', 55, 'delete-field', {iconCls: 'silk-delete'})
            ]
        });

        this.items = [
            this.fieldGrid
        ];

        this.callParent(arguments);
    },

    getEditorDialog: function() {
        var editorDialog = Ext.WindowMgr.get('fieldEditorDialog');
        if (OPF.isEmpty(editorDialog)) {
            editorDialog = Ext.create('OPF.core.component.editor.FieldEditorDialog', this);
            Ext.WindowMgr.register(editorDialog);
        } else {
            editorDialog.setGrid(this);
        }
        return editorDialog;
    },

    cleanFieldStore: function() {
        var fieldsStore = Ext.StoreManager.lookup('Fields');
        fieldsStore.removeAll();
    }

});