package net.firejack.platform.generate.beans.ipad;
/*
 * Firejack Open Flame - Copyright (c) 2012 Firejack Technologies
 *
 * This source code is the product of the Firejack Technologies
 * Core Technologies Team (Benjamin A. Miller, Oleg Marshalenko, and Timur
 * Asanov) and licensed only under valid, executed license agreements
 * between Firejack Technologies and its customers. Modification and / or
 * re-distribution of this source code is allowed only within the terms
 * of an executed license agreement.
 *
 * Any modification of this code voids any and all warranties and indemnifications
 * for the component in question and may interfere with upgrade path. Firejack Technologies
 * encourages you to extend the core framework and / or request modifications. You may
 * also submit and assign contributions to Firejack Technologies for consideration
 * as improvements or inclusions to the platform to restore modification
 * warranties and indemnifications upon official re-distributed in patch or release form.
 */


public interface iPad {
    public static final String BASE_ENTITY_CLASS = "GWEntity";
    public static final String ENUM_CLASS = "GWEnum *";

    public static final String GWPROPERTY_TYPE_UNKNOWN = "GWPropertyTypeUnknown";
    public static final String GWPROPERTY_TYPE_ENUM = "GWPropertyTypeEnum";
    public static final String GWPROPERTY_TYPE_TREE = "GWPropertyTypeTree";
    public static final String GWPROPERTY_TYPE_PARENT = "GWPropertyTypeParent";
    public static final String GWPROPERTY_TYPE_IMAGE = "GWPropertyTypeImage";
    public static final String GWPROPERTY_TYPE_TEXT = "GWPropertyTypeText";
    public static final String GWPROPERTY_TYPE_PASSWORD = "GWPropertyTypePassword";
    public static final String GWPROPERTY_TYPE_PHONE_NUMBER = "GWPropertyTypePhoneNumber";
    public static final String GWPROPERTY_TYPE_SSN = "GWPropertyTypeSSN";
    public static final String GWPROPERTY_TYPE_STRING = "GWPropertyTypeString";
    public static final String GWPROPERTY_TYPE_NUMBER = "GWPropertyTypeNumber";
    public static final String GWPROPERTY_TYPE_DATE = "GWPropertyTypeDate";
    public static final String GWPROPERTY_TYPE_TIME = "GWPropertyTypeTime";
    public static final String GWPROPERTY_TYPE_FULL_TIME = "GWPropertyTypeFullTime";
    public static final String GWPROPERTY_TYPE_FLAG = "GWPropertyTypeFlag";
    public static final String GWPROPERTY_TYPE_OBJECT = "GWPropertyTypeObject";
    public static final String GWPROPERTY_TYPE_LIST = "GWPropertyTypeList";

    public static final String GWACTION_TYPE_CREATE = "GWActionTypeCreate";
    public static final String GWACTION_TYPE_UPDATE = "GWActionTypeUpdate";
    public static final String GWACTION_TYPE_DELETE = "GWActionTypeDelete";
    public static final String GWACTION_TYPE_READ = "GWActionTypeRead";
    public static final String GWACTION_TYPE_READ_ALL = "GWActionTypeReadAll";
    public static final String GWACTION_TYPE_SEARCH = "GWActionTypeSearch";
    public static final String GWACTION_TYPE_ADVANCED_SEARCH = "GWActionTypeAdvancedSearch";

    public static final String GWPROPERTY_ATTRIBUTE_AUTOGENERATED = "GWPropertyAttributeAutogenerated";
    public static final String GWPROPERTY_ATTRIBUTE_DEFAULT = "GWPropertyAttributeDefault";


    String getName();

    String getFilePosition();
}
