/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package net.firejack.platform.generate.beans.ipad;


import net.firejack.platform.api.registry.model.FieldType;
import net.firejack.platform.core.model.registry.ParameterTransmissionType;

import static net.firejack.platform.api.registry.model.FieldType.LIST;
import static net.firejack.platform.api.registry.model.FieldType.OBJECT;

public class Property {
    private String name;
    private boolean address;
    private boolean autoGenerated;
    private boolean exclude;
    private FieldType fieldType;
    private PropertyType type;
    private Entity entity;
    private ParameterTransmissionType location;
    private String column;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isAddress() {
        return address;
    }

    public void setAddress(boolean address) {
        this.address = address;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public boolean isExclude() {
        return exclude;
    }

    public void setExclude(boolean exclude) {
        this.exclude = exclude;
    }

    public FieldType getFieldType() {
        return fieldType;
    }

    public void setFieldType(FieldType fieldType) {
        this.fieldType = fieldType;
    }

    public PropertyType getType() {
        return type;
    }

    public void setType(PropertyType type) {
        this.type = type;
    }

    public Entity getEntity() {
        return entity;
    }

    public void setEntity(Entity entity) {
        this.entity = entity;
    }

    public ParameterTransmissionType getLocation() {
        return location;
    }

    public void setLocation(ParameterTransmissionType location) {
        this.location = location;
    }

    public String getColumn() {
        return column;
    }

    public void setColumn(String column) {
        this.column = column;
    }

    public boolean isRelationship() {
        return fieldType == OBJECT || fieldType == LIST || type == PropertyType.PARENT;
    }

    public boolean isEnum() {
        return type == PropertyType.ENUM;
    }

    public String getDisplayName() {
        if (type == PropertyType.PARENT)
            return "";

        if (entity != null) {
            return entity.getDisplayName();
        }
        return "pk";
    }

    public String getTypeClass() {
        if (type == PropertyType.ENUM) {
            return iPad.ENUM_CLASS;
        } else if (fieldType == OBJECT) {
            return entity.getName() + " *";
        } else {
            return fieldType.getObjectiveC();
        }
    }
}
